### ISSUE TITLE
clang error

### ISSUE THREAD

**Issue by waleyzheng** [AlexDenisov/ToyClangPlugin#2]
hello，when i use 

``` bash
 $LLVM_HOME/llvm_build/bin/clang ../test.m \
  -Xclang -load \
  -Xclang lib/Debug/ToyClangPlugin.dylib \
  -Xclang -plugin \
  -Xclang ToyClangPlugin
```

the result is:

```
fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^
1 error generated.
```

so how to fix it?

**Comment by AlexDenisov** [comment]
macOS has a bit different approach regarding headers and search paths. You can have several versions of Xcode installed and you can compile for different platforms.
You should use `-isysroot` option to explicitly specify against which SDK to compile your file.

The following command should do the trick

``` bash
$LLVM_HOME/llvm_build/bin/clang ../test.m \
-Xclang -load \
-Xclang lib/Debug/ToyClangPlugin.dylib \
-Xclang -plugin \
-Xclang ToyClangPlugin \
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
```

Otherwise, please check which SDKs are installed and change the value of `isysroot` to correspond to your setup.
