### ISSUE TITLE
macro expand

### ISSUE THREAD

**Issue by WorldControl** [AlexDenisov/ToyClangPlugin#4]
can you give me an example about how to expand macro in the source code use clang API?

**Comment by AlexDenisov** [comment]
I would suggest asking this question either on stack overflow (https://stackoverflow.com), or on the mailing list (http://lists.llvm.org/mailman/listinfo/cfe-users), because:
1. I don't have an answer
2. It's out of scope of this repository
3. I do not understand the question.

Thank you for understanding.
